name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-test:
    name: "Build & Test"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.15'

      - name: Download Module Deps
        run: |
          go mod download

      - name: Build
        run: |
          go build -v

      - name: Test
        run: |
          go test -v ./...

  docker-image:
    name: "Docker Image"
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Image
        run: |
          docker build -t vpp-probe .

      - name: Try Image
        run: |
          docker run --rm -i vpp-probe

  run-integration:
    name: "Run Integration"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.15'

      - name: Download Module Deps
        run: |
          go mod download

      - name: Run Tests
        run: |
          go test -v ./test/integration/...
